# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.14-alpine3.23"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.14-alpine3.23"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.14-alpine3.23"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.14-alpine3.23"
  i386: "ghcr.io/home-assistant/i386-base-python:3.14-alpine3.23"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bambuddy add-on"
  org.opencontainers.image.description: "A powerful, self-hosted print archive and management system for Bambu Lab 3D printers."
  org.opencontainers.image.source: "https://github.com/hobbypunk90/homeassistant-addon-bambuddy"
  org.opencontainers.image.licenses: "MIT License"
args:
  BAMBUDDY_VERSION: "0.1.8.1"