name: "Bambuddy Slicer API (Bambu) (DEV)"
version: "02.07.01.57"
slug: bambuddy_bambu_studio_api_dev
stage: experimental
description: "(DEV) A headless Bambu Studio API sidecar container for Bambuddy Auto-Slicing."
url: "https://github.com/connormxy/homeassistant-addon-bambuddy#dev"
arch:
  - amd64
init: false
map:
  - share:rw
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Bambu Studio API Port (use this in Bambuddy settings)
